# Generated by Django 3.1.4 on 2020-12-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('tweets', '0002_auto_20201213_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photos.Photo'),
        ),
    ]
